### ISSUE TITLE
Capital Sharp S

### ISSUE THREAD

**Issue by opentype-RH** [productiontype/Spectral#1]
ẞ or SS is an orthographic/mapping choice. It shouldn’t be decided/forced on the glyph level. 
Just as the W unicode is for the character W and you wouldn’t put V+V in there and force people to use that. 
Just as the Æ is for the character Æ and you wouldn’t put A+E in there and force people to use that.
And so on …

<img width="378" alt="screen shot 2017-06-18 at 08 53 49" src="https://user-images.githubusercontent.com/29516339/27258805-ae4b1aaa-5404-11e7-8efe-d974f27af96f.png">

**Comment by opentype-RH** [comment]
Would love to hear your reasons for closing it. 

Typical case which demonstrates the “issue”:
A graphic designers will paste a text into InDesign and then applies caps styling for headlines. 
InDesign will use the default Unicode mapping and turn “Straße” into “STRASSE” for example. Now if the users wants this orthography, there is nothing else to do. 
But if the users wants a capital sharp S instead (and the font has that code point), he/she would replace the double-s with uni1E9E—the character specifically added to Unicode to achieve this. But your font then replaces “SS” with “SS”. How does that make any sense? At best, your user will be confused by this unexpected behaviour, at worst the user will feel mocked because you are technically forcing an unwanted orthography on him/her. 

And you don’t need to take my word for it. Look up the DIN Institute’s Unicode proposal for 1E91. The code point was specifically added to allow the distinction between ss and ß as SS and ẞ in uppercase. Yet, Spectral deliberately sabotages that by hiding that distinction. And that’s an “issue” worth reporting and fixing.

**Comment by fitojb** [comment]
I was about to report the same issue, then found this thread.

**Comment by opentype-RH** [comment]
Apple’s SF font has the same bug, which actually now proves my point here. Displayed in Apple’s font, my text is hard to understand because the Capital Sharp S I put in the text cannot be recognized as its own character anymore. 
At least Apple has NOT closed the bug report and will probably correct this problem. 

To further proof my point and show that this is not just my opinion, I attach a picture from the current edition of the most-used German dictionary Duden. It discusses the ß rules and puts the use of “ß” and “ss” in uppercase next to each other. The same text wouldn’t make any sense anymore when set in Spectral. 
<img width="445" alt="bildschirmfoto 2017-11-14 um 09 39 20" src="https://user-images.githubusercontent.com/29516339/32770476-2704965c-c920-11e7-89f5-0c1b3eec9a49.png">

**Comment by davelab6** [comment]
I agree, I would like to see this fixed

**Comment by moyogo** [comment]
+1
