### ISSUE TITLE
Small caps not working?

### ISSUE THREAD

**Issue by thibaultmalfoy** [productiontype/Spectral#10]
Hello,

Thank you for this beautiful typeface.

I'm having difficulties to render some text with small caps, using the following CSS:

```
.spectral {
font-family: "Spectral", georgia, serif;
font-kerning: normal;
font-feature-settings: "kern", "liga", "clig", "calt", "onum", "smcp";
}
```

and this link in the header:

```
<link href="https://fonts.googleapis.com/css?family=Spectral:400,400i" rel="stylesheet"> 
```

What am I doing wrong?

Thank you!

**Comment by productiontype** [comment]
Hey,
You might want to use the SC ("Small Caps") version of the fonts, which are designed for that purpose.
https://github.com/productiontype/Spectral/tree/master/fonts/sc

**Comment by davelab6** [comment]
Google Fonts strips non required opentype features
