### ISSUE TITLE
Types without the ligature

### ISSUE THREAD

**Issue by maudubem** [productiontype/Spectral#11]
hello,
i'd like some advise in how to use this font on a headline but without the ligature between the letters "f" and "l". The word is Influence, and i'd like to use the f and l together, with no ligatures on it.

**Comment by productiontype** [comment]
Hi Maud, 
I guess you are using InDesign? You can simply deactivate the "Standard ligatures".

**Select the text that contains the ligatures.**
**Click on the flyout menu on the Control Panel.**
**Deselect "Ligatures."**

**Comment by productiontype** [comment]
Usually you can disable ligatures in CSS like this:
* {
font-variant-ligatures: none;
}
