### ISSUE TITLE
U+02BE/U+02BF flipped

### ISSUE THREAD

**Issue by frankrolf** [productiontype/Spectral#13]
It seems that the half-rings are flipped in comparison to other typefaces (also, they are a little small, and perhaps too widely spaced).
![screen shot 2018-12-10 at 14 14 32](https://user-images.githubusercontent.com/2049645/49734880-fa994a00-fc85-11e8-8b82-61e3bebb1e37.png)

**Comment by productiontype** [comment]
Thanks, will investigate!

**Comment by moyogo** [comment]
They are flipped indeed. Their sidebearing should be much narrower too. Space them like letters or apostrophe/quotes.

**Comment by frankrolf** [comment]
I found a good reference for those: http://andreasmhallberg.github.io/typographyofaynandhamza/#fn:1

**Comment by dajare** [comment]
Just noticed this was fixed. I guess I should have come here rather than tweeting in Nov 2017! That'll teach me....

https://twitter.com/erajad/status/929396730038284289
