### ISSUE TITLE
Most of the modifier letters should be respaced

### ISSUE THREAD

**Issue by moyogo** [productiontype/Spectral#14]
Spotted after looking at #13.

Most of the modifier letters in Spectral should be respaced: 02BE, 02BF, 02C6, 02C7, 02C8, 02C9, 02CA, 02CB, 02CC, 02D8, 02D9, 02DA, 02DD.
![spectral](https://user-images.githubusercontent.com/1923747/49801647-a86a2e80-fd42-11e8-85d0-33d2815bfb51.png)

They are meant to be used among letters and should be spaced as letters or apostrophe/quotes.

02BB, 02BC are fine.
![spectral](https://user-images.githubusercontent.com/1923747/49797721-2d9c1600-fd38-11e8-9367-c1829aedd510.png)

**Comment by frankrolf** [comment]
Do you have test text for those modifiers? Real-world use would be much appreciated.

**Comment by moyogo** [comment]
Many of those are used in phonetic notations, a lot are withdrawn IPA symbols and some are non standard IPA. See [The principles of the International Phonetic Association](https://archive.org/details/principlesofinte00inteuoft) from 1921 for example, in particular the Chinese and Burmese specimen on [page 30](https://archive.org/details/principlesofinte00inteuoft/page/30).

ˈ and ˌ are still current IPA symbols.

Skolt Sami sometimes uses the modifier letter prime 02B9 ʹ, or alternatively the ASCII acute 00B4 ´ or the modifier letter acute 02CA ˊ. See for example [the Koltansaame page of the *Encyclopaedia of Saami Culture*](http://senc.hum.helsinki.fi/wiki/Koltansaame) which uses the modifier letter acute 02CA ˊ.

**Comment by frankrolf** [comment]
Thank you!

**Comment by frankrolf** [comment]
@mr-islam You may be interested in the link I shared in #13: https://github.com/productiontype/Spectral/issues/13#issuecomment-446183595

**Comment by mr-islam** [comment]
@frankrolf That was a great read, thank you for sharing!
