### ISSUE TITLE
Italics and bold not showing

### ISSUE THREAD

**Issue by nagymusic** [productiontype/Spectral#15]
I'm using Spectral to typeset text in[ Lilypond](http://lilypond.org/) music notation program. When used as a text typeface, Spectral displayed properly in the past. Given the recent update to 2.0, italics and bold are no longer showing (they appear to be hidden/not showing) when used with Lilypond. This happens both with Google and Github .ttf versions; the Github .otf version typesets regular font as bold. However, the older version 1.0 (still available for download at Font Squirrel) is causing the italics to display (show) properly. This is the first time that I encountered this inconsistency, so I'm not sure how to go around it.

My apology if this comment may not be appropriate for this list. Would you be able to point me in the right direction? I don't mind simply using the older version in my work, but would nevertheless welcome the opportunity to understand for what reasons the new version is no longer fully compatible.

**Comment by davelab6** [comment]
You could use googlefonts fontdiffenator to compare the v1 and v2 and
hopefully find out what in the name table is different
