### ISSUE TITLE
Accent placements are wrong in Cyrillic

### ISSUE THREAD

**Issue by peczony** [productiontype/Spectral#16]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/3784544/52794435-dd676a00-3080-11e9-8ff2-91646c5a6f8a.png">

Text for pasting:
```
Latin a with modifier: á
Cyrillic a with modifier: а́
```

Combining acute accent placement in Cyrillic should be the same as in Latin.

**Comment by kenmcd** [comment]
It does not work because there is no anchor on the top of the Cyrillic a.
But I am wondering why you would need an acute on top of a Cyrillic a.
Is there a Cyrillic language that uses that?

**Comment by productiontype** [comment]
#invalid

**Comment by productiontype** [comment]
#invalid

**Comment by peczony** [comment]
@kenmcd Russian and other languages use acute to denote [stress](https://en.wikipedia.org/wiki/Stress_(linguistics)#Spelling_and_notation_for_stress)
