### ISSUE TITLE
TrueType curve quality

### ISSUE THREAD

**Issue by jenskutilek** [productiontype/Spectral#2]
I noticed the TrueType conversion made the curves more bumpy than they need to be. If you compare the PS outlines from the UFOs with the TTFs, you can see a lot of differences.

This is not visible at normal text sizes, but as TTF is the only distribution format for the desktop fonts, I thought it may be worth noting.

TrueType with PostScript in the background:

![x0ca1123hp4i](https://user-images.githubusercontent.com/3185950/27380722-93e52b78-5680-11e7-99e9-201749abfb9e.png)

PS on the left, TT on the right:

![eycc7h6og2w7](https://user-images.githubusercontent.com/3185950/27380744-ad32ce82-5680-11e7-9f8d-59724069f329.png)

**Comment by davelab6** [comment]
That's odd because
https://github.com/productiontype/Spectral/blob/master/sources/generate.sh
suggests to be there should be good quality outlines
