### ISSUE TITLE
Old Style 0 Glyph Has Too Little Contrast

### ISSUE THREAD

**Issue by JNord03** [productiontype/Spectral#21]
It can't be just me: The old style 0 glyph in each of the weights looks way too thin compared to the other numerals. This happens on all the software I've tested and regardless of whether tabular or proportional numerals are selected.
Here are some screenshots from LibreOffice (bold weight) writer and MS Word (Spectral with lining figures on top, Spectral with old style figures in the center and Source Serif 4 with old style figures at the bottom):
<img width="213" alt="Libreoffice" src="https://user-images.githubusercontent.com/51972670/211533750-4e7de042-99e9-468b-ac99-fa123abbfbe9.png">
<img width="198" alt="MS Word" src="https://user-images.githubusercontent.com/51972670/211533755-6cb1e0f3-67db-4963-b31f-209c92ca753c.png">
The strokes at the right and left arches of the 0 counter should be much thicker and look more like the o glyph:
![0o](https://user-images.githubusercontent.com/51972670/211534662-31b7a97d-61dd-4336-872f-b8dd68787ec1.png)
I love Spectral, but this makes OSN practically useless.

**Comment by productiontype** [comment]
Hey @Elendil03 

Thanks for reaching out and bringing this font design issue to our attention. We're sorry if it's causing you any trouble.

After a good look, we've determined that the font is totally fine and works as intended. We totally understand that font design is important, but rest assured that this one is on point.

There are many fonts that use the reversed-contrast design "old-style zero", such as[ Stempel Garamond.](https://fontsinuse.com/typefaces/3487/stempel-garamond)

Let us know if you have any other question or concerns, happy to help and answer any questions.

Thanks for your continued support and appreciate your business!

Cheers,
Production Type
